"""Object template domain models."""

from netauto.core.objecttemplate.exceptions import (
    DuplicateObjectTemplateComponent,
    DuplicateObjectTemplateProperty,
    InheritedObjectTemplateComponentConflict,
    InheritedObjectTemplatePropertyConflict,
    InvalidObjectTemplate,
    InvalidObjectTemplateComponent,
    InvalidObjectTemplateIdentifier,
    InvalidObjectTemplateProperty,
    InvalidObjectTemplateVersion,
    InvalidObjectTemplateVersionTransition,
    MismatchedObjectTemplateVersion,
    ObjectTemplateAlreadyExists,
    ObjectTemplateComponentVersionNotFound,
    ObjectTemplateComponentVersionNotPublished,
    ObjectTemplateDataTypeVersionNotFound,
    ObjectTemplateDataTypeVersionNotPublished,
    ObjectTemplateInheritanceCycle,
    ObjectTemplateNotFound,
    ObjectTemplateParentNotFound,
    ObjectTemplateParentNotPublished,
    ObjectTemplatePersistenceError,
    ObjectTemplateSelfInheritance,
    ObjectTemplateVersionAlreadyExists,
    ObjectTemplateVersionNotFound,
)
from netauto.core.objecttemplate.models import (
    ObjectTemplate,
    ObjectTemplateComponent,
    ObjectTemplateProperty,
    ObjectTemplateVersion,
    ObjectTemplateVersionRef,
    ObjectTemplateVersionStatus,
)
from netauto.core.objecttemplate.repository import ObjectTemplateRepository
from netauto.core.objecttemplate.resolver import (
    ObjectTemplateInheritanceResolver,
    ObjectTemplateVersionLookup,
)
from netauto.core.objecttemplate.versioning import (
    DataTypeVersionLookup,
    ObjectTemplateVersioningService,
)

__all__ = [
    "DuplicateObjectTemplateComponent",
    "DuplicateObjectTemplateProperty",
    "InheritedObjectTemplateComponentConflict",
    "InheritedObjectTemplatePropertyConflict",
    "InvalidObjectTemplate",
    "InvalidObjectTemplateComponent",
    "InvalidObjectTemplateIdentifier",
    "InvalidObjectTemplateProperty",
    "InvalidObjectTemplateVersion",
    "InvalidObjectTemplateVersionTransition",
    "MismatchedObjectTemplateVersion",
    "ObjectTemplateAlreadyExists",
    "ObjectTemplate",
    "ObjectTemplateComponentVersionNotFound",
    "ObjectTemplateComponentVersionNotPublished",
    "ObjectTemplateDataTypeVersionNotFound",
    "ObjectTemplateDataTypeVersionNotPublished",
    "ObjectTemplateInheritanceCycle",
    "ObjectTemplateInheritanceResolver",
    "ObjectTemplateNotFound",
    "ObjectTemplateParentNotFound",
    "ObjectTemplateParentNotPublished",
    "ObjectTemplatePersistenceError",
    "ObjectTemplateRepository",
    "ObjectTemplateSelfInheritance",
    "ObjectTemplateComponent",
    "ObjectTemplateProperty",
    "ObjectTemplateVersion",
    "ObjectTemplateVersionAlreadyExists",
    "ObjectTemplateVersionLookup",
    "ObjectTemplateVersionNotFound",
    "ObjectTemplateVersionRef",
    "ObjectTemplateVersionStatus",
    "ObjectTemplateVersioningService",
    "DataTypeVersionLookup",
]
