"""initial M1 schema

Revision ID: 0001_m1_schema
Revises:
Create Date: 2026-08-14 23:37:37.482624
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_m1_schema"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "datatypes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("namespace", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("default_version", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "length(namespace) <= 255 AND namespace ~ "
            "'^[a-z][a-z0-9_]{0,63}(\\.[a-z][a-z0-9_]{0,63})*$'",
            name="ck_datatypes_namespace",
        ),
        sa.CheckConstraint("name ~ '^[a-z][a-z0-9_]{0,63}$'", name="ck_datatypes_name"),
        sa.CheckConstraint(
            "default_version IS NULL OR default_version > 0",
            name="ck_datatypes_default_version_positive",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace", "name", name="uq_datatypes_namespace_name"),
    )
    op.create_table(
        "object_lifecycle_events",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "occurred_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("transaction_timestamp()"),
            nullable=False,
        ),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("object_id", sa.UUID(), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("destination_object_id", sa.UUID(), nullable=True),
        sa.Column("destination_canonical_name", sa.Text(), nullable=True),
        sa.Column("slot_declaring_template_id", sa.UUID(), nullable=True),
        sa.Column("slot_name", sa.Text(), nullable=True),
        sa.Column("relationship_id", sa.UUID(), nullable=True),
        sa.Column("relationship_definition_id", sa.UUID(), nullable=True),
        sa.Column("relationship_name", sa.Text(), nullable=True),
        sa.Column(
            "before_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "after_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.CheckConstraint(
            "(kind = 'CREATED' AND before_state IS NULL "
            "AND after_state IS NOT NULL) OR "
            "(kind IN ('RENAME', 'DATA_CHANGE', 'SCHEMA_CHANGE') AND "
            "before_state IS NOT NULL AND after_state IS NOT NULL) OR "
            "(kind = 'DELETED' AND before_state IS NOT NULL "
            "AND after_state IS NULL) OR "
            "kind IN ('ATTACH_TO', 'DETACH_FROM', 'RELATIONSHIP_CREATED', "
            "'RELATIONSHIP_DELETED')",
            name="ck_lifecycle_events_state_shape",
        ),
        sa.CheckConstraint(
            "(kind IN ('CREATED', 'RENAME', 'DATA_CHANGE', 'SCHEMA_CHANGE', 'DELETED') "
            "AND destination_object_id IS NULL AND destination_canonical_name IS NULL "
            "AND slot_declaring_template_id IS NULL AND slot_name IS NULL "
            "AND relationship_id IS NULL AND relationship_definition_id IS NULL "
            "AND relationship_name IS NULL) OR "
            "(kind IN ('ATTACH_TO', 'DETACH_FROM') "
            "AND destination_object_id IS NOT NULL "
            "AND destination_canonical_name IS NOT NULL "
            "AND slot_declaring_template_id IS NOT NULL AND slot_name IS NOT NULL "
            "AND relationship_id IS NULL AND relationship_definition_id IS NULL "
            "AND relationship_name IS NULL AND before_state IS NULL "
            "AND after_state IS NULL) OR "
            "(kind IN ('RELATIONSHIP_CREATED', 'RELATIONSHIP_DELETED') "
            "AND destination_object_id IS NOT NULL "
            "AND destination_canonical_name IS NOT NULL "
            "AND relationship_id IS NOT NULL "
            "AND relationship_definition_id IS NOT NULL "
            "AND relationship_name IS NOT NULL "
            "AND slot_declaring_template_id IS NULL AND slot_name IS NULL "
            "AND before_state IS NULL AND after_state IS NULL)",
            name="ck_lifecycle_events_family_shape",
        ),
        sa.CheckConstraint(
            "after_state IS NULL OR jsonb_typeof(after_state) = 'object'",
            name="ck_lifecycle_events_after_state_object",
        ),
        sa.CheckConstraint(
            "before_state IS NULL OR jsonb_typeof(before_state) = 'object'",
            name="ck_lifecycle_events_before_state_object",
        ),
        sa.CheckConstraint(
            "kind IN ('CREATED', 'RENAME', 'DATA_CHANGE', 'SCHEMA_CHANGE', "
            "'ATTACH_TO', 'DETACH_FROM', 'RELATIONSHIP_CREATED', "
            "'RELATIONSHIP_DELETED', 'DELETED')",
            name="ck_lifecycle_events_kind",
        ),
        sa.CheckConstraint(
            "relationship_name IS NULL OR relationship_name ~ '^[a-z][a-z0-9_]{0,63}$'",
            name="ck_lifecycle_events_relationship_name",
        ),
        sa.CheckConstraint(
            "slot_name IS NULL OR slot_name ~ '^[a-z][a-z0-9_]{0,63}$'",
            name="ck_lifecycle_events_slot_name",
        ),
        sa.CheckConstraint(
            "destination_canonical_name IS NULL OR "
            "length(destination_canonical_name) BETWEEN 1 AND 255",
            name="ck_lifecycle_events_destination_name_length",
        ),
        sa.CheckConstraint(
            "length(canonical_name) BETWEEN 1 AND 255",
            name="ck_lifecycle_events_canonical_name_length",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_lifecycle_events_definition",
        "object_lifecycle_events",
        ["relationship_definition_id", "occurred_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_lifecycle_events_destination",
        "object_lifecycle_events",
        ["destination_object_id", "occurred_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_lifecycle_events_kind",
        "object_lifecycle_events",
        ["kind", "occurred_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_lifecycle_events_object",
        "object_lifecycle_events",
        ["object_id", "occurred_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_lifecycle_events_occurred",
        "object_lifecycle_events",
        ["occurred_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_lifecycle_events_relationship",
        "object_lifecycle_events",
        ["relationship_id", "occurred_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_lifecycle_events_relationship_name",
        "object_lifecycle_events",
        ["relationship_name", "occurred_at", "id"],
        unique=False,
        postgresql_where=sa.text("relationship_name IS NOT NULL"),
    )
    op.create_table(
        "object_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("namespace", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("abstract", sa.Boolean(), nullable=False),
        sa.Column("default_version", sa.Integer(), nullable=True),
        sa.Column("parent_template_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "length(namespace) <= 255 AND namespace ~ "
            "'^[a-z][a-z0-9_]{0,63}(\\.[a-z][a-z0-9_]{0,63})*$'",
            name="ck_object_templates_namespace",
        ),
        sa.CheckConstraint(
            "name ~ '^[a-z][a-z0-9_]{0,63}$'", name="ck_object_templates_name"
        ),
        sa.CheckConstraint(
            "default_version IS NULL OR default_version > 0",
            name="ck_object_templates_default_version_positive",
        ),
        sa.ForeignKeyConstraint(
            ["parent_template_id"],
            ["object_templates.id"],
            name="fk_object_templates_parent",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "namespace", "name", name="uq_object_templates_namespace_name"
        ),
    )
    op.create_index(
        "ix_object_templates_parent",
        "object_templates",
        ["parent_template_id"],
        unique=False,
    )
    op.create_table(
        "relationship_definitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("symmetric", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "datatype_versions",
        sa.Column("datatype_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("base_type", sa.Text(), nullable=False),
        sa.Column(
            "constraints", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.CheckConstraint(
            "base_type IN ('core.string', 'core.integer', 'core.number', "
            "'core.boolean', 'core.date', 'core.datetime', 'core.ip', "
            "'core.ip_prefix', 'core.byte_size')",
            name="ck_datatype_versions_base_type",
        ),
        sa.CheckConstraint(
            "jsonb_typeof(constraints) = 'object'",
            name="ck_datatype_versions_constraints_object",
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PUBLISHED', 'DEPRECATED')",
            name="ck_datatype_versions_status",
        ),
        sa.CheckConstraint(
            "revision > 0", name="ck_datatype_versions_revision_positive"
        ),
        sa.CheckConstraint("version > 0", name="ck_datatype_versions_version_positive"),
        sa.ForeignKeyConstraint(
            ["datatype_id"],
            ["datatypes.id"],
            name="fk_datatype_versions_datatype",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("datatype_id", "version"),
    )
    op.create_table(
        "object_template_versions",
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("parent_template_id", sa.UUID(), nullable=True),
        sa.Column("parent_version", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PUBLISHED', 'DEPRECATED')",
            name="ck_object_template_versions_status",
        ),
        sa.CheckConstraint(
            "(parent_template_id IS NULL AND parent_version IS NULL) OR "
            "(parent_template_id IS NOT NULL AND parent_version IS NOT NULL)",
            name="ck_object_template_versions_parent_pair",
        ),
        sa.CheckConstraint(
            "parent_version IS NULL OR parent_version > 0",
            name="ck_object_template_versions_parent_version_positive",
        ),
        sa.CheckConstraint(
            "revision > 0", name="ck_object_template_versions_revision_positive"
        ),
        sa.CheckConstraint(
            "version > 0", name="ck_object_template_versions_version_positive"
        ),
        sa.ForeignKeyConstraint(
            ["parent_template_id", "parent_version"],
            [
                "object_template_versions.template_id",
                "object_template_versions.version",
            ],
            name="fk_object_template_versions_parent_version",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["object_templates.id"],
            name="fk_object_template_versions_template",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("template_id", "version"),
    )
    op.create_index(
        "ix_object_template_versions_parent_version",
        "object_template_versions",
        ["parent_template_id", "parent_version"],
        unique=False,
    )
    # The two default-version FKs close intentional lineage/version cycles, so they
    # are created only after both sides of each composite reference exist.
    op.create_foreign_key(
        "fk_datatypes_default_version",
        "datatypes",
        "datatype_versions",
        ["id", "default_version"],
        ["datatype_id", "version"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_object_templates_default_version",
        "object_templates",
        "object_template_versions",
        ["id", "default_version"],
        ["template_id", "version"],
        ondelete="RESTRICT",
    )
    op.create_table(
        "relationship_resolutions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("relationship_definition_id", sa.UUID(), nullable=False),
        sa.Column("from_template_id", sa.UUID(), nullable=False),
        sa.Column("to_template_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "name ~ '^[a-z][a-z0-9_]{0,63}$'", name="ck_relationship_resolutions_name"
        ),
        sa.ForeignKeyConstraint(
            ["from_template_id"],
            ["object_templates.id"],
            name="fk_relationship_resolutions_from_template",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["relationship_definition_id"],
            ["relationship_definitions.id"],
            name="fk_relationship_resolutions_definition",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_template_id"],
            ["object_templates.id"],
            name="fk_relationship_resolutions_to_template",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id",
            "relationship_definition_id",
            name="uq_relationship_resolutions_id_definition",
        ),
        sa.UniqueConstraint(
            "relationship_definition_id",
            "from_template_id",
            "to_template_id",
            "name",
            name="uq_relationship_resolutions_semantic_child",
        ),
    )
    op.create_index(
        "ix_relationship_resolutions_from_template",
        "relationship_resolutions",
        ["from_template_id"],
        unique=False,
    )
    op.create_index(
        "ix_relationship_resolutions_to_template",
        "relationship_resolutions",
        ["to_template_id"],
        unique=False,
    )
    op.create_table(
        "relationships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("relationship_definition_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["relationship_definition_id"],
            ["relationship_definitions.id"],
            name="fk_relationships_definition",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id", "relationship_definition_id", name="uq_relationships_id_definition"
        ),
    )
    op.create_index(
        "ix_relationships_definition",
        "relationships",
        ["relationship_definition_id"],
        unique=False,
    )
    op.create_table(
        "object_template_components",
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("template_version", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("target_template_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "name ~ '^[a-z][a-z0-9_]{0,63}$'", name="ck_object_template_components_name"
        ),
        sa.CheckConstraint(
            "position > 0", name="ck_object_template_components_position_positive"
        ),
        sa.CheckConstraint(
            "template_version > 0",
            name="ck_object_template_components_template_version_positive",
        ),
        sa.ForeignKeyConstraint(
            ["target_template_id"],
            ["object_templates.id"],
            name="fk_object_template_components_target",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id", "template_version"],
            [
                "object_template_versions.template_id",
                "object_template_versions.version",
            ],
            name="fk_object_template_components_version",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("template_id", "template_version", "name"),
        sa.UniqueConstraint(
            "template_id",
            "template_version",
            "position",
            name="uq_object_template_components_position",
        ),
    )
    op.create_index(
        "ix_object_template_components_target",
        "object_template_components",
        ["target_template_id"],
        unique=False,
    )
    op.create_table(
        "object_template_properties",
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("template_version", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("datatype_id", sa.UUID(), nullable=False),
        sa.Column("datatype_version", sa.Integer(), nullable=False),
        sa.Column("value_mode", sa.Text(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column(
            "migration_default", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.CheckConstraint(
            "name ~ '^[a-z][a-z0-9_]{0,63}$'", name="ck_object_template_properties_name"
        ),
        sa.CheckConstraint(
            "value_mode IN ('SCALAR', 'LIST')",
            name="ck_object_template_properties_value_mode",
        ),
        sa.CheckConstraint(
            "datatype_version > 0",
            name="ck_object_template_properties_datatype_version_positive",
        ),
        sa.CheckConstraint(
            "position > 0", name="ck_object_template_properties_position_positive"
        ),
        sa.CheckConstraint(
            "required OR migration_default IS NULL",
            name="ck_object_template_properties_optional_default",
        ),
        sa.CheckConstraint(
            "template_version > 0",
            name="ck_object_template_properties_template_version_positive",
        ),
        sa.ForeignKeyConstraint(
            ["datatype_id", "datatype_version"],
            ["datatype_versions.datatype_id", "datatype_versions.version"],
            name="fk_object_template_properties_datatype_version",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id", "template_version"],
            [
                "object_template_versions.template_id",
                "object_template_versions.version",
            ],
            name="fk_object_template_properties_version",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("template_id", "template_version", "name"),
        sa.UniqueConstraint(
            "template_id",
            "template_version",
            "position",
            name="uq_object_template_properties_position",
        ),
    )
    op.create_index(
        "ix_object_template_properties_datatype_version",
        "object_template_properties",
        ["datatype_id", "datatype_version"],
        unique=False,
    )
    op.create_table(
        "objects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("template_version", sa.Integer(), nullable=False),
        sa.Column(
            "properties", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.CheckConstraint(
            "jsonb_typeof(properties) = 'object'", name="ck_objects_properties_object"
        ),
        sa.CheckConstraint(
            "length(canonical_name) BETWEEN 1 AND 255",
            name="ck_objects_canonical_name_length",
        ),
        sa.CheckConstraint(
            "template_version > 0", name="ck_objects_template_version_positive"
        ),
        sa.ForeignKeyConstraint(
            ["template_id", "template_version"],
            [
                "object_template_versions.template_id",
                "object_template_versions.version",
            ],
            name="fk_objects_template_version",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_objects_canonical_name_id",
        "objects",
        ["canonical_name", "id"],
        unique=False,
    )
    op.create_index(
        "ix_objects_template_version",
        "objects",
        ["template_id", "template_version"],
        unique=False,
    )
    op.create_table(
        "object_components",
        sa.Column("child_object_id", sa.UUID(), nullable=False),
        sa.Column("parent_object_id", sa.UUID(), nullable=False),
        sa.Column("slot_name", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "slot_name ~ '^[a-z][a-z0-9_]{0,63}$'",
            name="ck_object_components_slot_name",
        ),
        sa.CheckConstraint(
            "parent_object_id <> child_object_id", name="ck_object_components_not_self"
        ),
        sa.ForeignKeyConstraint(
            ["child_object_id"],
            ["objects.id"],
            name="fk_object_components_child",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_object_id"],
            ["objects.id"],
            name="fk_object_components_parent",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("child_object_id"),
    )
    op.create_index(
        "ix_object_components_parent_slot_child",
        "object_components",
        ["parent_object_id", "slot_name", "child_object_id"],
        unique=False,
    )
    op.create_table(
        "runtime_relationship_resolutions",
        sa.Column("relationship_id", sa.UUID(), nullable=False),
        sa.Column("relationship_definition_id", sa.UUID(), nullable=False),
        sa.Column("resolution_id", sa.UUID(), nullable=False),
        sa.Column("from_object_id", sa.UUID(), nullable=False),
        sa.Column("to_object_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_object_id"],
            ["objects.id"],
            name="fk_runtime_resolutions_from_object",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["relationship_id", "relationship_definition_id"],
            ["relationships.id", "relationships.relationship_definition_id"],
            name="fk_runtime_resolutions_relationship_definition",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resolution_id", "relationship_definition_id"],
            [
                "relationship_resolutions.id",
                "relationship_resolutions.relationship_definition_id",
            ],
            name="fk_runtime_resolutions_resolution_definition",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["to_object_id"],
            ["objects.id"],
            name="fk_runtime_resolutions_to_object",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("resolution_id", "from_object_id", "to_object_id"),
    )
    op.create_index(
        "ix_runtime_resolutions_from_object",
        "runtime_relationship_resolutions",
        ["from_object_id"],
        unique=False,
    )
    op.create_index(
        "ix_runtime_resolutions_relationship",
        "runtime_relationship_resolutions",
        ["relationship_id"],
        unique=False,
    )
    op.create_index(
        "ix_runtime_resolutions_to_object",
        "runtime_relationship_resolutions",
        ["to_object_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_runtime_resolutions_to_object",
        table_name="runtime_relationship_resolutions",
    )
    op.drop_index(
        "ix_runtime_resolutions_relationship",
        table_name="runtime_relationship_resolutions",
    )
    op.drop_index(
        "ix_runtime_resolutions_from_object",
        table_name="runtime_relationship_resolutions",
    )
    op.drop_table("runtime_relationship_resolutions")
    op.drop_index(
        "ix_object_components_parent_slot_child", table_name="object_components"
    )
    op.drop_table("object_components")
    op.drop_index("ix_objects_template_version", table_name="objects")
    op.drop_index("ix_objects_canonical_name_id", table_name="objects")
    op.drop_table("objects")
    op.drop_index(
        "ix_object_template_properties_datatype_version",
        table_name="object_template_properties",
    )
    op.drop_table("object_template_properties")
    op.drop_index(
        "ix_object_template_components_target", table_name="object_template_components"
    )
    op.drop_table("object_template_components")
    op.drop_index("ix_relationships_definition", table_name="relationships")
    op.drop_table("relationships")
    op.drop_index(
        "ix_relationship_resolutions_to_template", table_name="relationship_resolutions"
    )
    op.drop_index(
        "ix_relationship_resolutions_from_template",
        table_name="relationship_resolutions",
    )
    op.drop_table("relationship_resolutions")
    op.drop_constraint(
        "fk_object_templates_default_version",
        "object_templates",
        type_="foreignkey",
    )
    op.drop_constraint("fk_datatypes_default_version", "datatypes", type_="foreignkey")
    op.drop_index(
        "ix_object_template_versions_parent_version",
        table_name="object_template_versions",
    )
    op.drop_table("object_template_versions")
    op.drop_table("datatype_versions")
    op.drop_table("relationship_definitions")
    op.drop_index("ix_object_templates_parent", table_name="object_templates")
    op.drop_table("object_templates")
    op.drop_index(
        "ix_lifecycle_events_relationship_name",
        table_name="object_lifecycle_events",
        postgresql_where=sa.text("relationship_name IS NOT NULL"),
    )
    op.drop_index(
        "ix_lifecycle_events_relationship", table_name="object_lifecycle_events"
    )
    op.drop_index("ix_lifecycle_events_occurred", table_name="object_lifecycle_events")
    op.drop_index("ix_lifecycle_events_object", table_name="object_lifecycle_events")
    op.drop_index("ix_lifecycle_events_kind", table_name="object_lifecycle_events")
    op.drop_index(
        "ix_lifecycle_events_destination", table_name="object_lifecycle_events"
    )
    op.drop_index(
        "ix_lifecycle_events_definition", table_name="object_lifecycle_events"
    )
    op.drop_table("object_lifecycle_events")
    op.drop_table("datatypes")
    # ### end Alembic commands ###
