"""Object domain models."""

from netauto.core.object.exceptions import (
    AbstractObjectTemplateInstantiation,
    ComponentMembershipAlreadyExists,
    ComponentMembershipNotFound,
    ComponentOwnershipCycle,
    InvalidComponentMembership,
    InvalidObject,
    InvalidObjectPatch,
    MissingObjectMigrationPropertyValue,
    ObjectAlreadyExists,
    ObjectComponentSlotNotFound,
    ObjectComponentTemplateIncompatible,
    ObjectDataTypeVersionNotFound,
    ObjectMigrationBlocked,
    ObjectMigrationTargetVersionNotNewer,
    ObjectMigrationTargetVersionNotPublished,
    ObjectNotFound,
    ObjectPersistenceError,
    ObjectTemplateVersionNotPublished,
    ObjectValidationFailed,
    UnexpectedObjectMigrationPropertyValue,
)
from netauto.core.object.migration import (
    ObjectMigrationResult,
    ObjectTemplateMigrationAddedComponent,
    ObjectTemplateMigrationAddedProperty,
    ObjectTemplateMigrationAnalysis,
    ObjectTemplateMigrationBlockingChange,
    ObjectTemplateMigrationBlockingChangeKind,
)
from netauto.core.object.models import ComponentMembership, Object
from netauto.core.object.repository import ObjectRepository
from netauto.core.object.validation import (
    DataTypeVersionLookup,
    ObjectValidationEngine,
    ObjectValidationIssue,
    ObjectValidationResult,
)

__all__ = [
    "AbstractObjectTemplateInstantiation",
    "ComponentMembership",
    "ComponentOwnershipCycle",
    "ComponentMembershipAlreadyExists",
    "ComponentMembershipNotFound",
    "DataTypeVersionLookup",
    "InvalidObjectPatch",
    "InvalidComponentMembership",
    "InvalidObject",
    "MissingObjectMigrationPropertyValue",
    "Object",
    "ObjectAlreadyExists",
    "ObjectComponentSlotNotFound",
    "ObjectComponentTemplateIncompatible",
    "ObjectDataTypeVersionNotFound",
    "ObjectMigrationBlocked",
    "ObjectMigrationTargetVersionNotNewer",
    "ObjectMigrationResult",
    "ObjectMigrationTargetVersionNotPublished",
    "ObjectNotFound",
    "ObjectPersistenceError",
    "ObjectTemplateMigrationAddedComponent",
    "ObjectTemplateMigrationAddedProperty",
    "ObjectTemplateMigrationAnalysis",
    "ObjectTemplateMigrationBlockingChange",
    "ObjectTemplateMigrationBlockingChangeKind",
    "ObjectRepository",
    "ObjectTemplateVersionNotPublished",
    "ObjectValidationEngine",
    "ObjectValidationFailed",
    "ObjectValidationIssue",
    "ObjectValidationResult",
    "UnexpectedObjectMigrationPropertyValue",
]
